### ISSUE TITLE
SEO  text unblocking bad UX

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#20]
The seo details on home editor were v difficult to know what to write, or where it will show. 
Seo title to page title (prefill from shop name?)
Stuck what to write tooltip

**Comment by G-Bro** [comment]
What to write tooltips on prod description - shorter description
remove 'SEO' word
about you
about product
notes on how to write seo - prompt you with a question -> next question button

**Comment by martdog** [comment]
shorten the required length of spiel
