### ISSUE TITLE
My plan is to

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#27]
In the  settings address etc, does not currently take my address
Plus, change "my plan is to" to blank in the "tell us about your project," box

**Comment by G-Bro** [comment]
@martdog what do you mean by 'does not currently take my address'. Do you mean you enter your address but it doesn't save it?

**Comment by martdog** [comment]
@G-Bro  believe that the address wasn't there at time of clicking - went to old API settings page.

May have been bad link. Test payment / settings address link, check all good - if you happy it works, close.
