### ISSUE TITLE
Homepage save validation

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#29]
Saving homepage, validation not clear. Is can save without a pod - but no explain!

**Comment by G-Bro** [comment]
@martdog I've got a couple of potential solutions to the pod issue.

If you have no pods the (optional) message appears. After you add your first one it disappears.

![image](https://cloud.githubusercontent.com/assets/17454235/13464015/ef06099e-e086-11e5-9320-aadf67698087.png)
 
Or, along the lines of 'appear when needed':

![image](https://cloud.githubusercontent.com/assets/17454235/13464193/d9191936-e087-11e5-8573-0424b23d7878.png)

**Comment by martdog** [comment]
2 is nice and clean.

Add Pods (recommended)

Pods can hold images, links, products. Add 4 or more to your homepage to show off your top products, categories, pages, blogs or photos. You can change these around anytime.

**Comment by G-Bro** [comment]
@martdog What do you think?

![image](https://cloud.githubusercontent.com/assets/17454235/13466964/2de0a360-e094-11e5-86b8-9dc5832b04c1.png)

**Comment by martdog** [comment]
lovely - all I'd say is that the Add pods (recommended) in H style, with the add pods button in green below.

The concept of "adding a section-row" can be reused, I.e. if you want to add a top 4 etc.
