### ISSUE TITLE
Moderation - benefit of doubt

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#33]
Move to a benefit of doubt model? 99% will b legit
At least reduce impact of " in review" stage - maybe on prodpage, disclaimer t/ report till moderated

**Comment by G-Bro** [comment]
Products are disowned on front end until approved - message saying "awaiting approval"

Rejected products disappear.

**Comment by G-Bro** [comment]
Photoshop disclaimer on frontend for product and subdomain

**Comment by martdog** [comment]
![report](https://cloud.githubusercontent.com/assets/17437229/13357680/5f9fbac0-dca3-11e5-9d82-2dac6c8fa230.jpg)

**Comment by martdog** [comment]
@js-wheeler

**Comment by martdog** [comment]
Sorry - one more thing, unable to buy on front end until approved

**Comment by G-Bro** [comment]
@martdog Do we want it to say who made the product?
The creator is going to be the same for every product per subdomain. Seems a bit weird to say:
"this was made by Jimmy" 
"this was made by Jimmy" 
"this was made by Jimmy" 
etc. all through the store

**Comment by martdog** [comment]
ok np - my idea was through the eyes of an imaginary coca-cola brand lawyer viewing the prod page, so there was some accountability for creator who infringed their copyright. This message only during "due for review" time period

Thinking has moved on - in that we may be doing benefit of doubt moderation.

Think we should discuss @js-wheeler

**Comment by G-Bro** [comment]
Not yet available

Report button and form
Report form is on contact page

**Comment by G-Bro** [comment]
Report button still to come, but 'not yet available' message added and 'skip moderation queu' working. Removing urgent tag for now.

**Comment by G-Bro** [comment]
Everything is done except for reporting

Reporting incorporated into issue #96, so closing this
