### ISSUE TITLE
Which of the following best describes you - other

### ISSUE THREAD

**Issue by G-Bro** [Teemill/TMLL#53]
What if someone doesn't fit into one of the Teemill subgroups?

Do we need a generic subgroup? What do we show them on the dashboard banner?

**Comment by martdog** [comment]
Make list longer, Don't like "other" categories, they wreck the DB. Could have other - Add notes?
@js-wheeler

**Comment by martdog** [comment]
Other [please say what]

**Comment by js-wheeler** [comment]
What's the current list? Surely we can make it so that every fits into one of the options

**Comment by martdog** [comment]
@G-Bro ? Off top of head I have

Charity
Startup Brand
Band
App Developer
Illustrator
Graphic Designer
Artist
Photographer
Student
Entrepreneur
Internet Marketer

**Comment by G-Bro** [comment]
Current list is Band, Charity, Photographer, Artist, Illustrator, Designer and Developer.

I will add more

**Comment by G-Bro** [comment]
Actions to do: create new teemill client subgroups, add to the account_type lists
