### ISSUE TITLE
Descriptions length

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#7]
The description length is friction - almost stopped my test case from proceeding!! - reduce, or prompt / as the right question (JavaScript time?)

**Comment by martdog** [comment]
Merges with text prompt solution https://github.com/Teemill/TMLL/issues/50

**Comment by martdog** [comment]
Reduce SEO text description length

**Comment by G-Bro** [comment]
Product description minimum length reduced from 30 to 15, all other descriptions minimums reduced from 12 to 8
