### ISSUE TITLE
Issues Feedback Form

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#85]
Ability for people to feedback issues from anywhere in teemill backend > form shoots to either email (?) or github issue tracker.

Possible email, to prevent duplicates swamping?

Add to header

**Comment by martdog** [comment]
![top-right-feedback](https://cloud.githubusercontent.com/assets/17437229/13397952/0cc36380-def4-11e5-90a9-de9f627fc662.jpg)

**Comment by martdog** [comment]
![bug](https://cloud.githubusercontent.com/assets/17437229/13398180/0f7f9d7c-def5-11e5-90dc-4e0dd475c5f3.jpg)

**Comment by martdog** [comment]
popup means we can get current page / feature launched from
Perhaps pull in page title / URL to details
Also browser, version, device

**Comment by martdog** [comment]
Differentiate between bug OR  improvement / suggestion

**Comment by G-Bro** [comment]
![image](https://cloud.githubusercontent.com/assets/17454235/13400732/09154c5a-df01-11e5-89be-3706e181c57a.png)
![image](https://cloud.githubusercontent.com/assets/17454235/13400749/1c9e0bc2-df01-11e5-8d4a-6ac8c147e7a6.png)

**Comment by martdog** [comment]
cool thanks, grey tick!

**Comment by martdog** [comment]
ps. If there are multiple issues, please submit multiple tickets! One issue per ticket. If you send us ten, that's not a nuisance
