### ISSUE TITLE
cleaner "under construction / submit approval" top bar

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#87]
![store-under-construction](https://cloud.githubusercontent.com/assets/17437229/13402389/edaabd0e-df07-11e5-86e3-0d7927db5a47.jpg)

**Comment by G-Bro** [comment]
That digger image was copyrighted and I couldn't find another nice one, so I used a wrench instead.

![image](https://cloud.githubusercontent.com/assets/17454235/13468575/2ac1bd8e-e09b-11e5-84f3-5a455228671b.png)

**Comment by martdog** [comment]
@G-Bro  looks great, thankyou
