### ISSUE TITLE
H2 on welcome dynamic

### ISSUE THREAD

**Issue by martdog** [Teemill/TMLL#88]
This is your dashboard, where you find everything you need for Teemill. Start by making your first product 

- this needs dynamic

Send me list of stages, I will write a sentence for each 

M

**Comment by G-Bro** [comment]
@martdog stages are

Checklist phase:
Create product
Design store
Setup homepage
Create a category
Create menu
Payment settings
Update contacts
Launch

Moderation phase:
Awaiting approval
Rejected
Approved

Once a store reaches 'approved' it will permanently stay in that state

**Comment by martdog** [comment]
Create product

Design store
First product, check. Now it's time to get creative and design how your store is going to look. 

Setup homepage
Great progress so far. Next up get your homepage looking amazing now

Create a category
Categories help your customers find what they're looking for. Set up your first category now

Create menu
Use our handy menu editor to link all the parts of your store together

Payment settings
We need to make sure you get paid when you make a sale. Update details

Update contacts
Nearly there! Before we can launch this, it'd be nice to know who we're working with.Update details


Launch
Awesome! Your store is ready to start taking orders. Time to tell the world about it. Read marketing blogs

Moderation phase:
The first few times you submit content, our moderation team looks in on your content. This is normally the same day.

Awaiting approval


Rejected
We need a few tweaks before this meets Teemill's high quality standards.

Approved
Analyse sales and traffic, improve and upgrade your store and launch some marketing now.

**Comment by martdog** [comment]
@G-Bro
