### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by G-Bro** [Teemill/TMLL#93]
Priority urgent but leave till after all the other alpha stuff

Fix link between template and template elements
DELETE = true

Add link back to products

delete any orphan templates and template elements

**Comment by martdog** [comment]
@js-wheeler 
Do we need to consider templates and starting points in space proj?
has george given space any thought (ideas, things we havent thought of)

**Comment by G-Bro** [comment]
all existing orphans deleted
when custom products are deleted they will take any templates with them
